### PR TITLE
Use initial_properties

### PR DESCRIPTION
**Pull request by Niklp09**
- Use initial_properties
- Remove some obsolete files

### CODE REVIEW

**Comment by wsor4035** [comment]
if you want to remove the copyright files fine, but information should be moved to the license file

**Review by wsor4035 — APPROVED** [review]
should probably `copyright.txt`->`license[.extenion]`, otherwise seems good

**Comment by Niklp09** [comment]
Already taken by `LICENSE.txt` (LGPL 3.0 copy)

**Comment by wsor4035** [comment]
> Already taken by `LICENSE.txt` (LGPL 3.0 copy)

> License: GPL v3

hmm.......

**Review by wsor4035 — APPROVED** [review]
good enough for now, still an improvement

**Pull request merged**
